In [1]:
from src.data.sika import CustomImageDataset
from torch.utils.data import DataLoader
from torchvision import transforms
import torch
import os

os.chdir('../..')


In [2]:

# Define the transformations
transform = transforms.Compose([
    transforms.ToTensor(),
])

# Create the dataset
dataset = CustomImageDataset(
    data_path='./data/train',
    transform=transform
)

Error loading image Image_FHNW_00517.jpg


In [3]:
dataset.labels

[array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([3]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([3]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([3]),
 array([5]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([1]),
 array([5]),
 array([5]),
 array([1]),
 array([1]),
 array([1]),
 array([5]),
 array([5]),
 array([1]),
 array([1]),
 array([5]),
 array([4]),
 array([1]),
 array([1]),
 array([1]),

In [4]:
# Create the DataLoader
dataloader = DataLoader(
    dataset,
    batch_size=4,
    shuffle=True,
    num_workers=0
)

batch = dataloader.__iter__().__next__()

In [5]:
batch

[tensor([[[[0.1529, 0.1608, 0.1647,  ..., 0.1373, 0.1490, 0.1373],
           [0.1529, 0.1333, 0.1451,  ..., 0.1412, 0.1412, 0.1294],
           [0.1647, 0.1451, 0.1490,  ..., 0.1412, 0.1333, 0.1412],
           ...,
           [0.0000, 0.0000, 0.0078,  ..., 0.0275, 0.0078, 0.0353],
           [0.0000, 0.0039, 0.0157,  ..., 0.0549, 0.0431, 0.0392],
           [0.0196, 0.0000, 0.0157,  ..., 0.0706, 0.0941, 0.0431]],
 
          [[0.1725, 0.1804, 0.1843,  ..., 0.1569, 0.1647, 0.1529],
           [0.1725, 0.1569, 0.1647,  ..., 0.1608, 0.1569, 0.1451],
           [0.1843, 0.1647, 0.1686,  ..., 0.1608, 0.1490, 0.1569],
           ...,
           [0.0078, 0.0157, 0.0353,  ..., 0.0353, 0.0118, 0.0392],
           [0.0157, 0.0235, 0.0471,  ..., 0.0627, 0.0510, 0.0471],
           [0.0353, 0.0157, 0.0431,  ..., 0.0784, 0.1020, 0.0549]],
 
          [[0.1765, 0.1843, 0.1882,  ..., 0.1686, 0.1843, 0.1725],
           [0.1765, 0.1569, 0.1686,  ..., 0.1725, 0.1765, 0.1647],
           [0.1882, 0.16